# This workflow's only purpose is to integrate this project easily in my portfolio
# I would not recommend it for a real project or team development as it push the
# build directory in the repository wich is pointless.git status
name: build
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build FRONT
        run: npm install && npm run build
      - name: Commit
        run: |
          git config --global user.email "{{ secrets.EMAIL }}"
          git config --global user.name "Oriun"
          git add -f build
          git commit -am "Automatic build"
          git push
